site_name: Starlight - Development Documentation
site_url: https://fifthcirclestudios.github.io/Starlight-GDD/
site_author: Fifth Circle Studios, Jordan Pryor

# Repository
repo_name: FifthCircleStudios/Starlight-GDD
repo_url: https://github.com/FifthCircleStudios/Starlight-GDD

# Copyright
copyright: Copyright &copy; 2024 Fifth Circle Studios

nav:
    - Home: index.md
    - Getting Started: nav/getting-started.md
    - Settings:
      - nav/settings/custom-highlight.md
    - Development:
      - nav/development/development-guide.md
      - nav/development/release-notes.md


theme:
  name: dracula
  logo: "https://github.com/FifthCircleStudios/Starlight-GDD/blob/main/assets/Starlight_Logo.png"
  favicon: assets/img/favicon.ico